"""add multi-tenancy models

Revision ID: fd82f92fd054
Revises: 6f990b645bf8
Create Date: 2026-02-07 00:45:47.973475
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers
revision: str = 'fd82f92fd054'
down_revision: Union[str, None] = '6f990b645bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definitions',
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('graph_module', sa.String(length=255), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tier_restrictions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_type_version', 'agent_definitions', ['type', 'version'], unique=False)
    op.create_index(op.f('ix_agent_definitions_type'), 'agent_definitions', ['type'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('billing_email', sa.String(length=255), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), nullable=False),
    sa.Column('monthly_conversation_limit', sa.Integer(), nullable=False),
    sa.Column('overage_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('organization_api_keys',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_organization_api_keys_key_prefix'), 'organization_api_keys', ['key_prefix'], unique=False)
    op.create_table('agent_instances',
    sa.Column('store_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_definition_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('config_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deployed_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_definition_id'], ['agent_definitions.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_instances_public_key'), 'agent_instances', ['public_key'], unique=True)
    op.create_index(op.f('ix_agent_instances_store_id'), 'agent_instances', ['store_id'], unique=False)
    op.create_table('conversation_usage',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_instance_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('conversation_count', sa.Integer(), nullable=False),
    sa.Column('billed_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('billed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_instance_id'], ['agent_instances.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_org_month', 'conversation_usage', ['organization_id', 'month'], unique=True)
    op.create_index(op.f('ix_conversation_usage_organization_id'), 'conversation_usage', ['organization_id'], unique=False)
    op.add_column('conversations', sa.Column('agent_instance_id', sa.UUID(as_uuid=False), nullable=False))
    op.create_index(op.f('ix_conversations_agent_instance_id'), 'conversations', ['agent_instance_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'agent_instances', ['agent_instance_id'], ['id'])
    op.add_column('stores', sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False))
    op.create_index(op.f('ix_stores_organization_id'), 'stores', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'stores', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_index(op.f('ix_stores_organization_id'), table_name='stores')
    op.drop_column('stores', 'organization_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_agent_instance_id'), table_name='conversations')
    op.drop_column('conversations', 'agent_instance_id')
    op.drop_index(op.f('ix_conversation_usage_organization_id'), table_name='conversation_usage')
    op.drop_index('idx_usage_org_month', table_name='conversation_usage')
    op.drop_table('conversation_usage')
    op.drop_index(op.f('ix_agent_instances_store_id'), table_name='agent_instances')
    op.drop_index(op.f('ix_agent_instances_public_key'), table_name='agent_instances')
    op.drop_table('agent_instances')
    op.drop_index(op.f('ix_organization_api_keys_key_prefix'), table_name='organization_api_keys')
    op.drop_table('organization_api_keys')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_agent_definitions_type'), table_name='agent_definitions')
    op.drop_index('idx_agent_type_version', table_name='agent_definitions')
    op.drop_table('agent_definitions')
    # ### end Alembic commands ###
